name: py3-11_hn_analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - sparqlwrapper
  - pandas
  - matplotlib
  - ipykernel
  - ipywidgets
  - seaborn
  - plotly
  - ipyleaflet
  - networkx
  - itables
  - netgraph
  - pyvis
  - geopandas
  - geodatasets
  - pygwalker
  - pip
  - pip:
    - fanalysis


    
